### PR TITLE
Update to Ruby 2.7.1

### PR DESCRIPTION
**Pull request by Pontus4**

### CODE REVIEW

**Comment by Pontus4** [comment]
The app is using an old version of Feedjira (2.1.2). To use the latest version, deprecated methods have to be replaced. See

https://github.com/feedjira/feedjira/blob/master/CHANGELOG.md#300

**Comment by walro** [comment]
> The app is using an old version of Feedjira (2.1.2). To use the latest version, deprecated methods have to be replaced.

Think it could be reasonable to try to solve that, but perhaps in a follow-up PR.

**Comment by walro** [comment]
> Think it could be reasonable to try to solve that, but perhaps in a follow-up PR.

Created #7 for that.

**Review by walro — APPROVED** [review]
LGTM!

**Pull request merged**
